In [1]:
import pandas as pd

In [2]:
# Importando database
base = pd.read_csv('credit_data.csv')

In [3]:
# Estatísticas do database
base.describe()

        i#clientid        income          age          loan    c#default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [4]:
# Amostra dos dados
base.head()

   i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [5]:
# Verificando dados com idade negativa
base.loc[base['age'] < 0]

    i#clientid        income        age         loan  c#default
15          16  50501.726689 -28.218361  3977.287432          0
21          22  32197.620701 -52.423280  4244.057136          0
26          27  63287.038908 -36.496976  9595.286289          0

In [6]:
### Maneiras de contornar o problema das idades menores que zero

## 1) Apagar a coluna por inteiro (não recomendada, neste caso)
# base.drop('age', 1, inplace=True)

## 2) Apagar apenas os registros, por completo, que possuem essa incoerência
# base.drop(base[base.age < 0].index, inplace=True)

## 3) Preencher os valores com a média da coluna, apenas dos valores maiores que zero
media = base['age'][base.age > 0].mean()
base.loc[base.age < 0, 'age'] = media

In [7]:
# Verificando valores nulos
base.loc[pd.isnull(base['age'])]

    i#clientid        income  age         loan  c#default
28          29  59417.805406  NaN  2082.625938          0
30          31  48528.852796  NaN  6155.784670          0
31          32  23526.302555  NaN  2862.010139          0

In [8]:
# Divisão do dataset entre variáveis preditoras e target
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values

In [9]:
# Substituindo os valores missing pela média de cada coluna
from sklearn.preprocessing import Imputer

imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer.fit(previsores[:, 0:3])

previsores[:, 0:3] = imputer.transform(previsores[:, 0:3])

In [10]:
## Fazendo o escalonamento (normalização) dos atributos
from sklearn.preprocessing import StandardScaler

# Padronização
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

# Normalização
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# previsores = scaler.fit_transform(previsores)

In [11]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

C:\Users\ricar\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [12]:
# modelo SVM
classificadorSVM = SVC(kernel='rbf', C=2.0)
classificadorSVM.fit(previsores, classe)

SVC(C=2.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
# modelo Random Forest
classificadorRandomForest = RandomForestClassifier(n_estimators=40, criterion='entropy')
classificadorRandomForest.fit(previsores, classe)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=40, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [14]:
# modelo Redes Neurais
classificadorMLP = MLPClassifier(verbose=True, max_iter=500, tol=0.00001, solver='adam', hidden_layer_sizes=(100),
                                activation='relu', batch_size=200, learning_rate_init=0.001)
classificadorMLP.fit(previsores, classe)

Iteration 1, loss = 0.72035849
Iteration 2, loss = 0.63602671
Iteration 3, loss = 0.56394337
Iteration 4, loss = 0.50313629
Iteration 5, loss = 0.45188175
Iteration 6, loss = 0.40813349
Iteration 7, loss = 0.37093489
Iteration 8, loss = 0.33856815
Iteration 9, loss = 0.31082451
Iteration 10, loss = 0.28691854
Iteration 11, loss = 0.26596966
Iteration 12, loss = 0.24776331
Iteration 13, loss = 0.23159972
Iteration 14, loss = 0.21740847
Iteration 15, loss = 0.20489192
Iteration 16, loss = 0.19388192
Iteration 17, loss = 0.18405473
Iteration 18, loss = 0.17530849
Iteration 19, loss = 0.16746365
Iteration 20, loss = 0.16046641
Iteration 21, loss = 0.15392325
Iteration 22, loss = 0.14811347
Iteration 23, loss = 0.14276336
Iteration 24, loss = 0.13779041
Iteration 25, loss = 0.13329146
Iteration 26, loss = 0.12918808
Iteration 27, loss = 0.12536366
Iteration 28, loss = 0.12186515
Iteration 29, loss = 0.11868634
Iteration 30, loss = 0.11567650
Iteration 31, loss = 0.11295215
Iteration 32, loss = 0.11031054
Iteration 33, loss = 0.10790309
Iteration 34, loss = 0.10565507
Iteration 35, loss = 0.10345318
Iteration 36, loss = 0.10146930
Iteration 37, loss = 0.09951595
Iteration 38, loss = 0.09773898
Iteration 39, loss = 0.09603583
Iteration 40, loss = 0.09432262
Iteration 41, loss = 0.09269585
Iteration 42, loss = 0.09111717
Iteration 43, loss = 0.08971588
Iteration 44, loss = 0.08832035
Iteration 45, loss = 0.08703463
Iteration 46, loss = 0.08569792
Iteration 47, loss = 0.08438661
Iteration 48, loss = 0.08312634
Iteration 49, loss = 0.08201446
Iteration 50, loss = 0.08085403
Iteration 51, loss = 0.07972533
Iteration 52, loss = 0.07866291
Iteration 53, loss = 0.07759734
Iteration 54, loss = 0.07664079
Iteration 55, loss = 0.07556997
Iteration 56, loss = 0.07465066
Iteration 57, loss = 0.07368271
Iteration 58, loss = 0.07285191
Iteration 59, loss = 0.07196535
Iteration 60, loss = 0.07097360
Iteration 61, loss = 0.07011478
Iteration 62, loss = 0.06928061
Iteration 63, loss = 0.06840398
Iteration 64, loss = 0.06763200
Iteration 65, loss = 0.06684854
Iteration 66, loss = 0.06608082
Iteration 67, loss = 0.06532223
Iteration 68, loss = 0.06451546
Iteration 69, loss = 0.06384662
Iteration 70, loss = 0.06314626
Iteration 71, loss = 0.06240510
Iteration 72, loss = 0.06166322
Iteration 73, loss = 0.06104533
Iteration 74, loss = 0.06043321
Iteration 75, loss = 0.05975793
Iteration 76, loss = 0.05911547
Iteration 77, loss = 0.05842642
Iteration 78, loss = 0.05783861
Iteration 79, loss = 0.05728368
Iteration 80, loss = 0.05665657
Iteration 81, loss = 0.05606397
Iteration 82, loss = 0.05553795
Iteration 83, loss = 0.05499872
Iteration 84, loss = 0.05444273
Iteration 85, loss = 0.05390438
Iteration 86, loss = 0.05339585
Iteration 87, loss = 0.05285517
Iteration 88, loss = 0.05243968
Iteration 89, loss = 0.05187545
Iteration 90, loss = 0.05127761
Iteration 91, loss = 0.05082769
Iteration 92, loss = 0.05036779
Iteration 93, loss = 0.04993681
Iteration 94, loss = 0.04936699
Iteration 95, loss = 0.04896922
Iteration 96, loss = 0.04859741
Iteration 97, loss = 0.04821854
Iteration 98, loss = 0.04766070
Iteration 99, loss = 0.04722156
Iteration 100, loss = 0.04683280
Iteration 101, loss = 0.04643498
Iteration 102, loss = 0.04614555
Iteration 103, loss = 0.04563140
Iteration 104, loss = 0.04533709
Iteration 105, loss = 0.04484868
Iteration 106, loss = 0.04448521
Iteration 107, loss = 0.04409335
Iteration 108, loss = 0.04375698
Iteration 109, loss = 0.04331096
Iteration 110, loss = 0.04299289
Iteration 111, loss = 0.04260211
Iteration 112, loss = 0.04234504
Iteration 113, loss = 0.04193361
Iteration 114, loss = 0.04161972
Iteration 115, loss = 0.04123950
Iteration 116, loss = 0.04096213
Iteration 117, loss = 0.04076125
Iteration 118, loss = 0.04026000
Iteration 119, loss = 0.03992391
Iteration 120, loss = 0.03958280
Iteration 121, loss = 0.03930314
Iteration 122, loss = 0.03896287
Iteration 123, loss = 0.03869611
Iteration 124, loss = 0.03852727
Iteration 125, loss = 0.03806736
Iteration 126, loss = 0.03772498
Iteration 127, loss = 0.03743070
Iteration 128, loss = 0.03719071
Iteration 129, loss = 0.03687599
Iteration 130, loss = 0.03661748
Iteration 131, loss = 0.03655362
Iteration 132, loss = 0.03615519
Iteration 133, loss = 0.03589113
Iteration 134, loss = 0.03567813
Iteration 135, loss = 0.03539170
Iteration 136, loss = 0.03508064
Iteration 137, loss = 0.03487682
Iteration 138, loss = 0.03471476
Iteration 139, loss = 0.03435127
Iteration 140, loss = 0.03416483
Iteration 141, loss = 0.03392833
Iteration 142, loss = 0.03375823
Iteration 143, loss = 0.03351111
Iteration 144, loss = 0.03338386
Iteration 145, loss = 0.03305353
Iteration 146, loss = 0.03292737
Iteration 147, loss = 0.03264644
Iteration 148, loss = 0.03247219
Iteration 149, loss = 0.03220432
Iteration 150, loss = 0.03208101
Iteration 151, loss = 0.03183873
Iteration 152, loss = 0.03174629
Iteration 153, loss = 0.03164632
Iteration 154, loss = 0.03128657
Iteration 155, loss = 0.03106053
Iteration 156, loss = 0.03090928
Iteration 157, loss = 0.03075336
Iteration 158, loss = 0.03055015
Iteration 159, loss = 0.03038401
Iteration 160, loss = 0.03020031
Iteration 161, loss = 0.02999862
Iteration 162, loss = 0.02991934
Iteration 163, loss = 0.02966126
Iteration 164, loss = 0.02951319
Iteration 165, loss = 0.02934062
Iteration 166, loss = 0.02924365
Iteration 167, loss = 0.02902340
Iteration 168, loss = 0.02891681
Iteration 169, loss = 0.02887933
Iteration 170, loss = 0.02878151
Iteration 171, loss = 0.02847598
Iteration 172, loss = 0.02828335
Iteration 173, loss = 0.02811617
Iteration 174, loss = 0.02801264
Iteration 175, loss = 0.02782417
Iteration 176, loss = 0.02766115
Iteration 177, loss = 0.02752786
Iteration 178, loss = 0.02740412
Iteration 179, loss = 0.02721241
Iteration 180, loss = 0.02711185
Iteration 181, loss = 0.02702297
Iteration 182, loss = 0.02689660
Iteration 183, loss = 0.02678988
Iteration 184, loss = 0.02660048
Iteration 185, loss = 0.02645615
Iteration 186, loss = 0.02635038
Iteration 187, loss = 0.02630614
Iteration 188, loss = 0.02612636
Iteration 189, loss = 0.02600155
Iteration 190, loss = 0.02584503
Iteration 191, loss = 0.02570918
Iteration 192, loss = 0.02556809
Iteration 193, loss = 0.02548313
Iteration 194, loss = 0.02528979
Iteration 195, loss = 0.02539764
Iteration 196, loss = 0.02512527
Iteration 197, loss = 0.02501842
Iteration 198, loss = 0.02486584
Iteration 199, loss = 0.02474038
Iteration 200, loss = 0.02467194
Iteration 201, loss = 0.02457323
Iteration 202, loss = 0.02440083
Iteration 203, loss = 0.02425894
Iteration 204, loss = 0.02421103
Iteration 205, loss = 0.02407748
Iteration 206, loss = 0.02389384
Iteration 207, loss = 0.02389825
Iteration 208, loss = 0.02372881
Iteration 209, loss = 0.02369448
Iteration 210, loss = 0.02357520
Iteration 211, loss = 0.02347853
Iteration 212, loss = 0.02331720
Iteration 213, loss = 0.02334225
Iteration 214, loss = 0.02322085
Iteration 215, loss = 0.02327589
Iteration 216, loss = 0.02309601
Iteration 217, loss = 0.02286983
Iteration 218, loss = 0.02271541
Iteration 219, loss = 0.02277848
Iteration 220, loss = 0.02251887
Iteration 221, loss = 0.02241545
Iteration 222, loss = 0.02233471
Iteration 223, loss = 0.02227061
Iteration 224, loss = 0.02217662
Iteration 225, loss = 0.02207555
Iteration 226, loss = 0.02202673
Iteration 227, loss = 0.02197098
Iteration 228, loss = 0.02190386
Iteration 229, loss = 0.02173367
Iteration 230, loss = 0.02162244
Iteration 231, loss = 0.02158633
Iteration 232, loss = 0.02147234
Iteration 233, loss = 0.02137392
Iteration 234, loss = 0.02130391
Iteration 235, loss = 0.02128393
Iteration 236, loss = 0.02113600
Iteration 237, loss = 0.02112080
Iteration 238, loss = 0.02094524
Iteration 239, loss = 0.02085539
Iteration 240, loss = 0.02080105
Iteration 241, loss = 0.02080221
Iteration 242, loss = 0.02062853
Iteration 243, loss = 0.02054809
Iteration 244, loss = 0.02048737
Iteration 245, loss = 0.02038957
Iteration 246, loss = 0.02034955
Iteration 247, loss = 0.02020842
Iteration 248, loss = 0.02015258
Iteration 249, loss = 0.02008689
Iteration 250, loss = 0.02014410
Iteration 251, loss = 0.01996824
Iteration 252, loss = 0.01993624
Iteration 253, loss = 0.01977311
Iteration 254, loss = 0.01968175
Iteration 255, loss = 0.01968563
Iteration 256, loss = 0.01960087
Iteration 257, loss = 0.01949889
Iteration 258, loss = 0.01937381
Iteration 259, loss = 0.01932768
Iteration 260, loss = 0.01933091

Iteration 261, loss = 0.01921049
Iteration 262, loss = 0.01915991
Iteration 263, loss = 0.01913728
Iteration 264, loss = 0.01910620
Iteration 265, loss = 0.01892180
Iteration 266, loss = 0.01888669
Iteration 267, loss = 0.01881706
Iteration 268, loss = 0.01875969
Iteration 269, loss = 0.01864634
Iteration 270, loss = 0.01866750
Iteration 271, loss = 0.01857147
Iteration 272, loss = 0.01848208
Iteration 273, loss = 0.01837847
Iteration 274, loss = 0.01838340
Iteration 275, loss = 0.01839270
Iteration 276, loss = 0.01838769
Training loss did not improve more than tol=0.000010 for two consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=0.0001, batch_size=200, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=100, learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=1e-05, validation_fraction=0.1,
       verbose=True, warm_start=False)

In [15]:
# Salvando modelos já treinados para aplicações comerciais
import pickle

In [16]:
pickle.dump(classificadorSVM, open('svm_finalizado.sav', 'wb'))

In [17]:
pickle.dump(classificadorRandomForest, open('random_forest_finalizado.sav', 'wb'))

In [18]:
pickle.dump(classificadorMLP, open('mlp_finalizado.sav', 'wb'))